name: GitHub Pages Deployment

on:
  push:
    branches:
      - flamingoBlocks

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Setup SSH to install dependencies
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Create production build
        env:
          REACT_APP_NETWORK: ${{ secrets.REACT_APP_NETWORK }}
          REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
          REACT_APP_URL_MAINNET: ${{ secrets.REACT_APP_URL_MAINNET }}
          REACT_APP_URL_RINKEBY: ${{ secrets.REACT_APP_URL_RINKEBY }}
          REACT_APP_API_URL_MAINNET: ${{ secrets.REACT_APP_API_URL_MAINNET }}
          REACT_APP_API_URL_RINKEBY: ${{ secrets.REACT_APP_API_URL_RINKEBY }}
          REACT_APP_MEDIA_URL_MAINNET: ${{ secrets.REACT_APP_MEDIA_URL_MAINNET }}
          REACT_APP_MEDIA_URL_RINKEBY: ${{ secrets.REACT_APP_MEDIA_URL_RINKEBY }}
          REACT_APP_MEDIA_URL_MAINNET_THUMB: ${{ secrets.REACT_APP_MEDIA_URL_MAINNET_THUMB }}
          REACT_APP_MEDIA_URL_RINKEBY_THUMB: ${{ secrets.REACT_APP_MEDIA_URL_RINKEBY_THUMB }}
        run: npm run build

      - name: Deploy to GitHub Pages site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: ${{ github.event.head_commit.message }}
