name: GitHub Pages Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Setup SSH to install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create production build
        env:
          REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: ${{ github.event.head_commit.message }}
          # cname: flamingo-ab.dev.thelao.com